- name: 1. install java 
  apt: name=openjdk-8-jdk state=present

- name: Set JAVA_HOME
  lineinfile: dest=/etc/environment
              regexp=''
              insertafter=EOF
              line="JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"

- name: Verify Java Version
  action: shell /usr/bin/java -version
  register: java
  changed_when: no
  tags:
    - verify

